services:
  mwnz-api:
    image: carlpetermeyer/mwnz-api:latest
    build:
      context: .
      dockerfile: Mwnz.Api/Dockerfile
    container_name: mwnz-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
